### ISSUE TITLE
returns not correct plainText value after all input value is deleted

### ISSUE THREAD

**Issue by minbelapps** [AndrewRedican/react-json-editor-ajrm#100]
Version: 2.5.9

if user deletes all input text, for example press "Cntr + All => Delete"  the callback returns "\n" value instead of empty string. With debugger I saw, that in short time JsonEditor shows 3 empty numeric values, so I suppose it's the reason why this "\n" comes from. After that JsonEditor change display to 0 numeric values (I suppose it gets the state I need: empty plainText) but callBack is not fired back :( 

The possible solutions: 

1. Avoid intermediate position with 3 displayed empty lines
2. Send callback after last change (no callback is sent back after Editor changes state from 3 empty lines to 0).

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
