### ISSUE TITLE
Editor validate without error and accept Javascript input like {s:"bla"}

### ISSUE THREAD

**Issue by minbelapps** [AndrewRedican/react-json-editor-ajrm#101]
Version: 2.5.9

Editor transforms JSON to javascript. For example I could paste Json string, but Editor displays as Javascript code. It's not big issue, but still, it's the JSON editor. Good stuff is hear, that callback function returns real JSON stringified value. 

In other words: situation, user wants just to validate some JSON value '{s:"bla"}', but that value is not correct JSON object, it's javascript Object, so the user paste it on Editor, editor shows, that it's OK, but actually that input is not valid, for example this will throw exception : JSON.parse('{s:"bla"}');
Valid JSON value should be '{"s":"bla"}'.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
