### ISSUE TITLE
after "Cnt +Z" not always callback event is fired automatically

### ISSUE THREAD

**Issue by minbelapps** [AndrewRedican/react-json-editor-ajrm#102]
Version: 2.5.9

If I change input value by keyword commands "Cnt +Z" call back is not fired automatically. I have added dynamic submit buttons and they are disabled, if no value provided. For example, user deletes everything with "Contr + all => delete", then pres "Cntr + Z" , the Editor shows some Json value in editor window, but submit button is disabled as callback event is not fired. This editor is on modal, so user closes the modal and only then the event is fired back.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
