### ISSUE TITLE
Not correct error line is shown

### ISSUE THREAD

**Issue by minbelapps** [AndrewRedican/react-json-editor-ajrm#103]
Version: 2.5.9

Not correct line is shown. For example my failure is in line under line number 7, but marked the 6 line and message says, that 6th line is causing error. I suppose the reason is, that lines starts by index 1 and validate'or is based on 0 index system. Please, fix so easy mistakes. Version 2.5.9 and I found 4 bugs in one day.

**Comment by AndrewRedican** [comment]
@minbelapps I have read your feedback (a little too late).  I think the easiest thing to do if you need something changed rather quickly is to submit a PR yourself.

I don't see reproduction steps or the expected bug format. I am closing this in favor of a new issue if it is still relevant.
