### ISSUE TITLE
Feature Request - Trailing Commas

### ISSUE THREAD

**Issue by nickerlan** [AndrewRedican/react-json-editor-ajrm#104]
Please, add support of trailing commas. 

It is very often situation to fix when I prepare some JSobj in vscode and then paste it to editor

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
