### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by giorgi-m** [AndrewRedican/react-json-editor-ajrm#105]
1. What version of RJEA are you using (react-json-editor-ajrm version)?  
2.5.9
2. What operating system and processor architecture are you using? 
Ubuntu
3. What did you do?
Type wrong JSON
4. What did you expect to see? 
...
5. What did you see instead? 
I saw the JSON object with messed up styles. Details below.

Initially you can see here I have a valid JSON object:

![screenshot from 2019-02-27 11-10-13](https://user-images.githubusercontent.com/41240312/53472240-8f8b3280-3a80-11e9-96d0-86aaee1db7c0.png)

Then I typed something which would make the JSON invalid:

![screenshot from 2019-02-27 11-10-38](https://user-images.githubusercontent.com/41240312/53472275-a467c600-3a80-11e9-8065-e436ca7174f3.png)

See the keyword "island" (near "mobile" keyword). You can see the output in the above image is messed up, which makes the component difficult to use.
Can you solve this somehow? Maybe not reformat the JSON in case there is error?

**Comment by AndrewRedican** [comment]
@giorgi-m there is a limitation on the logic parsing the string, unfortunately.

There is no quick fix for this. I have been working on a new parser as of six months ago, but I reckon it is going to be a while until that is complete since I work on it pretty much on my free time.
