### ISSUE TITLE
Resizeable editor

### ISSUE THREAD

**Issue by filiphoeven** [AndrewRedican/react-json-editor-ajrm#106]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
2.5.9

Would it be possible to add "resize" functionality to the editor like a textarea (bottom-left handle that allows the user to drag and resize the editor?
https://www.w3schools.com/cssref/css3_pr_resize.asp

**Comment by AndrewRedican** [comment]
I can't see why not. Although, there seem to be other items taking higher priority. The easiest thing to do if you want a quick resolution is to create a PR yourself. I would be happy to review it.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
