### ISSUE TITLE
Autosize editor

### ISSUE THREAD

**Issue by filiphoeven** [AndrewRedican/react-json-editor-ajrm#107]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.9

Is it possible to have the editor vertically grow/shrink automatically based on the content?
To avoid losing unnecessary space in a form.

**Comment by AndrewRedican** [comment]
I can't see why not. Although, there seem to be other items taking higher priority. The easiest thing to do if you want a quick resolution is to create a PR yourself. I would be happy to review it.
