### ISSUE TITLE
Japanese locale strings

### ISSUE THREAD

**Issue by MasakiFUJISAWA** [AndrewRedican/react-json-editor-ajrm#108]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
-> 2.5.9

2. What operating system and processor architecture are you using? *REQUIRED
-> Mac OS Mojave 10.14.4

3. What did you do? *REQUIRED
-> I imported locale/jpn and showJapanese error messages.

4. What did you expect to see? *REQUIRED
-> I saw some unnatural Japanese expressions.

5. What did you see instead? *REQUIRED
-> I would like to improve those Japanese messages more naturally.

---
DETAILS:
This component is quite cool.

To start using this, I have a request to update Japanese locale strings.

Most of all Japanese are perfect.
Could you consider to improve only some strings as follows?

> {
	format: "{reason} {line}行目",
	symbols: {
		colon: "コロン",           // :
		comma: "コンマ",           // ,
		semicolon: "セミコロン",   // ;
		slash: "スラッシュ",           // /  relevant for comment syntax support
		backslash: "バックスラッシュ",   // \  relevant for escaping character
		brackets: {
			round: "丸括弧",   // ( )
			square: "角括弧", // [ ]
			curly: "波括弧",   // { }
			angle: "山括弧"    // < >
		},
		period: "期間",            // . Also known as full point, full stop, or dot
		quotes: {
			single: "シングルクォート", // '
			double: "ダブルクォート", // "
			grave: "バッククォート"   // ` used on Javascript ES6 Syntax for String Templates
		},
		space: "スペース",           //       
		ampersand: "アンパサンド",   //	&
		asterisk: "アスタリスク",     //	*  relevant for some comment sytanx
		at: "アット",            //	@  multiple uses in other coding languages including certain data types
		equals: "イコール",    //	=
		hash: "ハッシュ",             //	#
		percent: "パーセント",       //	%
		plus: "プラス",             //	+
		minus: "マイナス",           //	−
		dash: "ダッシュ",             //	-
		hyphen: "ハイフン",         //	−
		tilde: "チルダ",           //	~
		underscore: "アンダースコア", //	_
		bar: "バー",      //	|
	},
	types: {
		key: "キー",
		value: "値",
		number: "数",
		string: "文字列",
		primitive: "プリミティブ",
		boolean: "ブール値",
		character: "キャラクター",
		integer: "整数",
		array: "配列",
		float: "浮動小数点数"
		//... Reference: https://en.wikipedia.org/wiki/List_of_data_structures
	},
	invalidToken: {
		tokenSequence: {
			prohibited: "'{firstToken}'トークンの後に '{secondToken}'トークンを続けることはできません",
			permitted: "'{firstToken}'トークンの後には '{secondToken}'トークンしか続けることができません"
		},
		termSequence: {
			prohibited: "{firstTerm}の後に{secondTerm}を続けることはできません。",
			permitted: "{firstTerm}には必ず{secondTerm}が続かなければなりません。"
		},
		double: "'{token}'トークンの後に別の '{token}'トークンを続けることはできません",
		useInstead: "'{badToken}'トークンは受け入れられません。 代わりに '{goodToken}'を使用してください",
		unexpected: "予期しない '{token}'トークンが見つかりました"
	},
	brace: {
		curly: {
			missingOpen: "左波括弧'{'がありません",
			missingClose: "左波括弧'{'に対応する右波括弧'}'がありません",
			cannotWrap: "'{token}'トークンを 波括弧'{}'で囲むことはできません"
		},
		square: {
			missingOpen: "左角括弧'['がありません",
			missingClose: "左角括弧'['に対応する右角括弧']'がありません",
			cannotWrap: "'{token}'トークンを 角括弧'[]'で囲むことはできません"
		}
	},
	string: {
		missingOpen: "開始文字列 '{quote}'トークンがないか無効です",
		missingClose: "終了文字列 '{quote}'トークンがないか無効です",
		mustBeWrappedByQuotes: "文字列は引用符で囲む必要があります",
		nonAlphanumeric: "英数字以外のトークン '{token}'は文字列表記の外側では使用できません",
		unexpectedKey: "文字列の位置で予期しないキーが見つかりました"
	},
	key: {
		numberAndLetterMissingQuotes: "数字で始まり、文字を含むキーは引用符で囲む必要があります",
		spaceMissingQuotes: "スペースを含むキーは引用符で囲む必要があります",
		unexpectedString: "キーの位置で予期しない文字列が見つかりました"	
	},
	noTrailingOrLeadingComma: "配列やオブジェクトの先頭や末尾にコンマをつけることはできません"
};

There are some ways to call curly brackets. So I revised besed on the following wiki page.
[wiki page](https://ja.wikipedia.org/wiki/%E6%8B%AC%E5%BC%A7)

For other strings, I wrote based on my experience.
Thank you.

**Comment by AndrewRedican** [comment]
@MasakiFUJISAWA 

Amazing, thanks for providing this feedback. I know it's rather a late reply. I'll keep this under consideration.

I no longer actively maintain this project, but I am working on a rewrite. [discussion](https://github.com/enio-ireland/enio/discussions/61)
