### ISSUE TITLE
Global Variable for DarkTheme or LightTheme

### ISSUE THREAD

**Issue by gdo** [AndrewRedican/react-json-editor-ajrm#11]
Hello,

Is it possible to have a global definition of the themes.

Perhaps something like <JSONInput colors='darkTheme' /> (with single quote so the parameter is a string and not an object like in this definition <JSONInput colors={darkTheme} />)

Thanks

**Comment by AndrewRedican** [comment]
In other words, you'd like a shorthand property that provide an identifier as to which built-in theme to use. I am thinking on providing a `theme` property in which you can pass on a string.

We'll probably want to make it so that you can select a `theme` but also override any color.

**Comment by AndrewRedican** [comment]
This feature has been added to RJEA as of version 2.4.1.
