### ISSUE TITLE
"\n" converted to "n" in string values of placeholder (=> editor will CORRUPT string values)

### ISSUE THREAD

**Issue by mandelcode** [AndrewRedican/react-json-editor-ajrm#111]
Version: 2.5.9

set placeholder to 
{
    s: "a-\n-a"
}

displays in editor :
{
   s: "a-n-a"
}

if edited, the wrong "a-n-a" value is passed to onChange

**Comment by Mr-Albert** [comment]
@mandelcode have you found a solution to this?

**Comment by MartinJesu** [comment]
I am also facing the same above issue. Any solution for this ?

**Comment by mandelcode** [comment]
No, we switched to another editor (jsoneditor-react).

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
