### ISSUE TITLE
Display in double-quotes instead of single quotes as per JSON standard

### ISSUE THREAD

**Issue by tomslot** [AndrewRedican/react-json-editor-ajrm#112]
the content is rendered as 

{  foo: 'bar' }

instead of 

{ "foo": "bar"}, with double quotes around strings as required by JSON standard

**Comment by sortegam** [comment]
+1

**Comment by xiyanfeixu** [comment]
+1

**Comment by ZengTianShengZ** [comment]
+1

**Comment by AndrewRedican** [comment]
Closing in favor of https://github.com/AndrewRedican/react-json-editor-ajrm/issues/120
