### ISSUE TITLE
Error when pasting string content wrapped in `<>`

### ISSUE THREAD

**Issue by vernak2539** [AndrewRedican/react-json-editor-ajrm#113]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
    - `react-json-editor-ajrm@2.5.9`
2. What operating system and processor architecture are you using? 
    - Mac OSX
3. What did you do? 
    - Copied `{ test: '<o>' }` into the editor
4. What did you expect to see? 
    - expected to see the content I posted formatted correctly
5. What did you see instead? 
    -  `Unrecognized node: {child: o}`
<img width="732" alt="Screenshot 2019-09-27 at 12 57 10" src="https://user-images.githubusercontent.com/521270/65767669-68840480-e126-11e9-9852-214bf208db37.png">

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
