### ISSUE TITLE
I want to keep the input in the wrong format

### ISSUE THREAD

**Issue by nanyawei** [AndrewRedican/react-json-editor-ajrm#114]
i want 
```
{
  name: 'a',
  g
}
```

not
```
{
  name: 'a',g}
```
Is there any way?

**Comment by vejandla** [comment]
@nanyawei did you figure out a solution for this?

**Comment by bbemis017** [comment]
I also don't like how it reformats like that when there is a syntax error. I find it makes the editor frustrating to use.

Has anyone looked into this issue in the code yet, or have any ideas why this happens?

**Comment by shaharjacob** [comment]
I also have that problem that the json is re-formatting s.t it hard to understand

**Comment by vejandla** [comment]
I looked at the code a bit. But, unfortunately, couldn't figure out. If you have any pointers please let me know. Happy to work on it. @bbemis017

**Comment by bbemis017** [comment]
I'm not really familiar with this codebase but I did look into this about a month ago. Sorry if my notes are aren't 100% right I probably should have posted this a while ago.

I focused debugging a specific example of broken json, a trailing `}` like I showed in the screen capture above. I found that in this section:
https://github.com/AndrewRedican/react-json-editor-ajrm/blob/7e9b63353e9148dd425bef9952e66698f20b863a/src/index.js#L1493-L1498

a line break and indent is being dropped, messing up everything after the syntax error. An incredibly dirty fix for this specific case on line 1498 could be:
`buffer.markup += (_adjustment + newSpan(i,token,_depth) + newLineBreakAndIndent());`

But of course there are multiple permutations on how something like this could occur so I didn't see an easy fix. 

Full Disclosure: After reading the code I decided to switch to a different library instead
https://www.npmjs.com/package/jsoneditor
https://www.npmjs.com/package/jsoneditor-react

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
