### ISSUE TITLE
autofocus !is it possible to make autofocus in this editor?

### ISSUE THREAD

**Issue by lmichratsimbazafy** [AndrewRedican/react-json-editor-ajrm#115]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2. What operating system and processor architecture are you using? *REQUIRED
3. What did you do? *REQUIRED
4. What did you expect to see? *REQUIRED
5. What did you see instead? *REQUIRED

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
