### ISSUE TITLE
Unexpected '\' token found

### ISSUE THREAD

**Issue by OwnGhy** [AndrewRedican/react-json-editor-ajrm#116]
1. version: 2.5.9
2. system: Mac OS Catalina
3. input something like `{a: '\s'}` to JSONInput component
4. expect: this case should not report error.
5. instead: got Error `Unexpected '\' token found`.

**Comment by andrienpecson** [comment]
Same issue I am trying to also add regex expression but got an `Unexpected '\' token found`.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
