### ISSUE TITLE
Uncaught TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by RonWang21** [AndrewRedican/react-json-editor-ajrm#117]
Hi, when I put in a JSON like this: "{a: 1}{".
I think the problem is with the second open "{".
The error is "Uncaught TypeError: Cannot read property 'string' of undefined".

This problem is already mentioned by @maynir in #20 

Would really like your help.

**Comment by AndrewRedican** [comment]
@RonWang21 could you provide a screenshot stack trace from the console log and formal reproduction steps. I will then prioritize this.
