### ISSUE TITLE
Some keys are wrapped in single-quotes others are not wrapped.

### ISSUE THREAD

**Issue by ariestav** [AndrewRedican/react-json-editor-ajrm#118]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.9

2. What operating system and processor architecture are you using? *REQUIRED
macOS 10.15.15

3. What did you do? *REQUIRED
I inject a valid JSON object into the editor area.  I noticed that in some of the objects that I am displaying into the editor, some key names are wrapped with single quotes while others are not wrapped with anything.   For example like the following:

<img width="399" alt="Screen Shot 2020-07-14 at 11 22 55 AM" src="https://user-images.githubusercontent.com/1365971/87450649-5f382b80-c5c4-11ea-962f-5a78020fddb6.png">

4. What did you expect to see? *REQUIRED
I expected to see either none of the keys wrapped in quotes, or all of the keys wrapped in quotes.  Is there a setting that let's us decide how we want the keys to be rendered to the display?

5. What did you see instead? *REQUIRED
Some of the keys are wrapped in quotes while others are not.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
