### ISSUE TITLE
Quoted Booleans not being allowed

### ISSUE THREAD

**Issue by willits8** [AndrewRedican/react-json-editor-ajrm#119]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.4.2
2. What operating system and processor architecture are you using?  Windows 10 (Intel Core i7-8650U)
3. What did you do? Pasted, the below value into the editor. (attempted to pass a boolean string ("false") as a value).
`{
  "externalAccountId": "tn-green09268",
  "academicYear": "2020-2021",
  "apSettingName": "ENABLE_SYNC_SECTIONS",
  "value": "false",
  "applyCriteria": "ALWAYS",
  "enabled": true,
  "createdBy": "HL"
}`
4. What did you expect to see?  a validated JSON string, as this is valid JSON (RFC 8259)
5. What did you see instead? Received validation error of "primitive can only follow '[' ':' ',' tokens at line 5"

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
