### ISSUE TITLE
Please update README example to include an `id` field, because JSONInput throws an exception

### ISSUE THREAD

**Issue by ellis** [AndrewRedican/react-json-editor-ajrm#13]
1. What version of RJEA are you using (react-json-editor-ajrm version)?

2.3.3

2. What operating system and processor architecture are you using?

Mac, Intel.

3. What did you do?

Tried an example like on the README:

```
<JSONInput
        placeholder = {{a: 1}}
        height      = '550px'
    />
```

4. What did you expect to see?

A working editor.

5. What did you see instead?

An exception related to missing `id`.

By adding the `id` field to `<JSONInput>`, the error went away.

**Comment by AndrewRedican** [comment]
Thanks @ellis. I'll be updating it shortly!

**Comment by AndrewRedican** [comment]
This has been updated. Thanks for the feedback.
