### ISSUE TITLE
Feature request: having onBlur feature

### ISSUE THREAD

**Issue by tonynguyenit18** [AndrewRedican/react-json-editor-ajrm#133]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
   2.5.10
2. What operating system and processor architecture are you using? 
   MacOS Sierra
3. What did you do? 
   Move the mouse away the RJEA component
4. What did you expect to see?
  onBlur is passed as a props and executed
5. What did you see instead?
  RJEA does not support onBlur props at the moment, it will trigger onChange instead

Thank you all for great json editor project, I have migrated form another json editor lib to RJEA, in our UX we synchronise data when moving the mouse away from the component by trigger onBlur event ONLY. It would be thankful if you can make RJEA support onBlur.

I am new to contribution and I want to take a chance to make this happen if you don't mind.

**Comment by rongyadong** [comment]
Oh, that is a really good feature if we have. Normally, if we need this onBlur we have to add by ourselves. If we can get this as a build-in API that would be amazing!
