### ISSUE TITLE
Text render issue

### ISSUE THREAD

**Issue by mirzasofthouse** [AndrewRedican/react-json-editor-ajrm#136]
Steps to reproduce:
- Type 

> "ONE":1 {{ New line with SHIFT + ENTER }}
"TWO":2

Expected:
- Error with the typed text

Result:
<img width="417" alt="Screenshot 2020-09-08 at 18 56 04" src="https://user-images.githubusercontent.com/34437978/92506173-5602be00-f205-11ea-8d78-213d117d1f36.png">

**Comment by mason-cognitiv** [comment]
try adding comma after each line to make it valid JSON
