### ISSUE TITLE
when object has string value containing double quoted substring, the substring is ignore

### ISSUE THREAD

**Issue by caopengau** [AndrewRedican/react-json-editor-ajrm#137]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
latest
2. What operating system and processor architecture are you using? *REQUIRED
macOS Catalina, Intel's x64
3. What did you do? *REQUIRED
using this library as a component in our app
4. What did you expect to see? *REQUIRED
the substring wrapped with double quote should be displayed/handled correctly
5. What did you see instead? *REQUIRED
the substring are ignored with only \'' instead(slash, single quote, single quote).

Eg.
if the the object looks like this: 
{
 text: "this is a sentence with "double quoted text", the double quoted text will be mishandled"
}

the editor will show something like this: 
{
 text: "this is a sentence with \'', the double quoted text will be mishandled"
}

**Comment by kopax** [comment]
Same error here

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
