### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by OperatorJack** [AndrewRedican/react-json-editor-ajrm#138]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
"^2.5.10"

2. What operating system and processor architecture are you using?
Windows 10. Ryzen 7 processor.

3. What did you do? 
I created a create-react-app project with typescript enabled. I passed an object to the editor which contains a bigint property. 

4. What did you expect to see?
I expected to see the bigint formatted as a string, number, or something else.

5. What did you see instead?
I received an exception. JSON.Stringify does not support stringifying bigints without an overload to handle that type. 
```
TypeError: Do not know how to serialize a BigInt
JSONInput.tokenize
H:/Repositories/MorrowBrowser/morrow-browser/node_modules/react-json-editor-ajrm/es/index.js:1720
  1717 | 
  1718 | if (!('nodeType' in something)) {
  1719 |   let buffer = {
> 1720 |     inputText: JSON.stringify(something),
       | ^  1721 |     position: 0,
  1722 |     currentChar: '',
  1723 |     tokenPrimary: '',
```

To prevent an exception, something like this could be used:
```JavaScript
JSON.stringify(
      obj,
      (key, value) => (typeof value === "bigint" ? value.toString() : value) // return everything else unchanged
);
```
Although a better solution would be preferred.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
