### ISSUE TITLE
Unable to parse string value "null"

### ISSUE THREAD

**Issue by KinTsang** [AndrewRedican/react-json-editor-ajrm#14]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.2.2
2. What operating system and processor architecture are you using? Sierra 10.12.6
3. What did you do?
Inputted object:
```
{
animal: "cat",
type: "null",
}
```

4. What did you expect to see? Accepts it as a correct JSON object
5. What did you see instead?
> primitive can only follow `[``:``,` tokens at line 2

**Comment by AndrewRedican** [comment]
Hi @KinTsang thanks for the feedback.

This has been fixed in the latest react-json-editor-ajrm version `2.4.3`.
