### ISSUE TITLE
Can't resolve 'react-json-editor-ajrm'

### ISSUE THREAD

**Issue by brightsider** [AndrewRedican/react-json-editor-ajrm#140]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.11
2. What operating system and processor architecture are you using? 
macOS 10.15.7
3. What did you do?
Update from 2.5.10 to 2.5.11
4. What did you expect to see?
Working library
5. What did you see instead?
Can't resolve 'react-json-editor-ajrm'

After back to 2.5.10 library start working.

**Comment by silentbalanceyh** [comment]
I met this issue also. When I upgrade to 2.5.11, it's working for me. But after upgrade to 2.5.11, this issue happen

Can't resolve 'react-json-editor-ajrm'

Here are temp solution

import JSONInput from 'react-json-editor-ajrm/src'

Above line is working, but it's not very prefer.

**Comment by johnson-byjus** [comment]
same issue for me But even` import JSONInput from 'react-json-editor-ajrm/src'` didt work
had to do `import JSONInput from 'react-json-editor-ajrm/dist';`

**Comment by inX95** [comment]
@AndrewRedican 
In your version 2.5.11, the entry file you specified is index.js, but what you actually build is in dist/index.js. 2.5.10 There is no dist directory, and it is directly tiled, causing us to quote errors.Please rebuild version

**Comment by gus-solji** [comment]
Ya la libreria no sirve en la version 2.5.11, por favor hacer de nuevo la versión para que ya no falle.

The library doesn't work in version 2.5.11, please rebuild version, is very important

<img width="979" alt="Screen Shot 2020-10-12 at 17 00 21" src="https://user-images.githubusercontent.com/28521187/95797331-7e6e5400-0cac-11eb-8519-924d318e4a96.png">

**Comment by johnson-byjus** [comment]
> Ya la libreria no sirve en la version 2.5.11, por favor hacer de nuevo la versión para que ya no falle.
> 
> The library doesn't work in version 2.5.11, please rebuild version, is very important
> 
> <img alt="Screen Shot 2020-10-12 at 17 00 21" width="979" src="https://user-images.githubusercontent.com/28521187/95797331-7e6e5400-0cac-11eb-8519-924d318e4a96.png">

user version 2.5.10

**Comment by ksinas** [comment]
Please rebuild version

**Comment by MMachado-uy** [comment]
+1

**Comment by gmacmaster** [comment]
+1

**Comment by AndrewRedican** [comment]
Hi all, 

My apologies for the incorrect publish. Please use bump to the latest version `2.5.13`.

I will be adding Github actions to the project automate few things such as validating changes that are ready for publishing and actually publish automatically to prevent this mistake from happening again.
