### ISSUE TITLE
Scientific Notation is invalid JSON 4.2424e-10

### ISSUE THREAD

**Issue by mason-cognitiv** [AndrewRedican/react-json-editor-ajrm#141]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
     ^2.5.10
2. What operating system and processor architecture are you using? 
     Catalina 10.15.6, 2.3 GHz Quad-Core Intel Core i7
3. What did you do? 
     Input the value as 4.2424e-10 into the JSON editor
<img width="437" alt="Screen Shot 2020-10-16 at 3 37 09 PM" src="https://user-images.githubusercontent.com/42151351/96319773-76245a80-0fc5-11eb-9557-278e166cda9c.png">
4. What did you expect to see? 
     Expected it to be valid JSON
5. What did you see instead?
     An error occurred.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
