### ISSUE TITLE
Incorrectly parsing quotes

### ISSUE THREAD

**Issue by ksinas** [AndrewRedican/react-json-editor-ajrm#142]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.13
2. What operating system and processor architecture are you using? *REQUIRED
Cloud
3. What did you do? *REQUIRED
had a parameter text in my object which contained double quotes
4. What did you expect to see? *REQUIRED
original text stored in the object
 ```
{
  text: 'I should be able to "quote something".'
}
```
5. What did you see instead? *REQUIRED
```
{
  text: 'I should be able to \''.'
}
```
Here's a link to codesandbox
[https://codesandbox.io/s/frosty-leavitt-o9kyd](https://codesandbox.io/s/frosty-leavitt-o9kyd)

**Comment by kopax** [comment]
Same error here.

**Comment by swapster** [comment]
The same

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
