### ISSUE TITLE
Performance problems with large JSON

### ISSUE THREAD

**Issue by CMonjo** [AndrewRedican/react-json-editor-ajrm#143]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.13 (lastest version)

2. What operating system and processor architecture are you using?
Mac OS (+ Google Chrome)

3. What did you do?
I have been using the package for 1 year but recently I have been trying to copy / paste large JSON within the editor (14000 lines). The page stops completely and I can't do anything more. So I tried with 2000 lines but the problem is the same.
To make sure it didn't come from me I created a new page with just this in it:

<img width="646" alt="Screenshot 2020-11-03 at 15 47 05" src="https://user-images.githubusercontent.com/31744890/97999825-195dd800-1dec-11eb-9c7b-e32c2c2b5356.png">

4. What did you expect to see?
Be able to have a visual load the time to process all the data

5. What did you see instead?
As explained, the window crashes completely and you have to wait a good minute (for 2000 lines) before seeing the page usable again.

I saw that 1 issue and 1 pr had were made in relation to the problem but they date from 2018
Issue : [https://github.com/AndrewRedican/react-json-editor-ajrm/issues/75](url)
PR : [https://github.com/AndrewRedican/react-json-editor-ajrm/pull/78](url)

Hoping to find a solution! Thank you for this package which is really great !! :)

**Comment by vejandla** [comment]
@CMonjo I bumped into the same issue recently. Did you find any solution?

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.

There is a known limitation to the amount of data that can be analyzed and rendered in the browser. You will have to limit the amount of data given to the component. This will be addressed in the rewrite.
