### ISSUE TITLE
Wrong JSON validation cause Missing/invalid closing string ''' token at line 438 due to valid json string =>  "This string will bug : \"OAUTH\""

### ISSUE THREAD

**Issue by kopax** [AndrewRedican/react-json-editor-ajrm#144]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 

2.5.13

2. What operating system and processor architecture are you using? 

Debian Buster amd64

3. What did you do? 

I am editing a large json

4. What did you expect to see? 

I expect to be able to remove a key/value(string) without problem

5. What did you see instead? 

It complains with an error: `Missing/invalid closing string ''' token at line 438`

> Note: I am removing a single line in a middle of an object, and the json is still valid, however, I am seeing a validation issue making this module a bit problematic for editing json.

Edit:

This is the string that cause issues:

```json
{
  "author": "John Doe",
  "description": "CRM and a in house single-sign-on protocole \"OAuth2 API\".\nsee less"
}
```

## Reproduction

https://codesandbox.io/s/broken-flower-5tjwe

Remove the first line and see the error with valid json.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
