### ISSUE TITLE
When the elements in the array are pure strings, do not automatically wrap

### ISSUE THREAD

**Issue by BaronCoder** [AndrewRedican/react-json-editor-ajrm#145]
1. When the element under the array attribute in the JSON data is a pure string, the string will not wrap automatically, and setting word-break in the browser is also invalid.
![image](https://user-images.githubusercontent.com/28944332/100180209-a50de480-2f12-11eb-82c2-e3375ae119e0.png)
![image](https://user-images.githubusercontent.com/28944332/100180498-409f5500-2f13-11eb-86e7-4fe9d4c71c99.png)

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
