### ISSUE TITLE
Editor freezes when we make a bigger change

### ISSUE THREAD

**Issue by shreeshtiwari2** [AndrewRedican/react-json-editor-ajrm#146]
I am using the latest version **2.5.13**.
I am working on **Windows 10, Chrome 86**, also tried it on Edge browser
I am using the package in one of my application and it freezes when we make change in like 2 objects at once, for example if a json contains array of objects and from that array **if we remove 2 objects at once then it freezes the application** and this doesn't only happen on Prod, it happens on local machine as well

I expect to see the change faster like we make the change in text field and then validation should run on the changed text.

I see that Editor becomes unusable and we have to wait quite for a long time to see it usable again for the application.

**Comment by faizan-tariq** [comment]
Facing the same issue

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
