### ISSUE TITLE
cut > paste - causes Error

### ISSUE THREAD

**Issue by wwitekk** [AndrewRedican/react-json-editor-ajrm#149]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.13 (example from master: example\webpack-project\)

2. What operating system and processor architecture are you using? *REQUIRED
Issue exists on Windows 10 Intel core I3; Browsers: Chrome, Opera, Edge
The issue does **not** exists on MacBook (browsers: Chrome, Opera, Mozilla, Safari)

3. What did you do? *REQUIRED
Preparation:
- Download master
- navigate to example\webpack-project
- npm i
- npm start

In Browser:
- open localhost:8080
- focus on editor field
- ctr+a
- ctrl+x
- ctrl+v

4. What did you expect to see? *REQUIRED
Original json editor content

5. What did you see instead? *REQUIRED
Original editor content with 'Non-alphanumeric token '' is not allowed outside string notation at line 1' error

![image](https://user-images.githubusercontent.com/4947059/102779579-c7b9de80-4394-11eb-9c8f-b49c1297ca9b.png)

Regards

Witold

**Comment by kolarski** [comment]
Happens in latest Firefox (89.0 (64-bit) at the time).

**Comment by Jaydeep9979** [comment]
has there been any updates on this ?

**Comment by sOoN92** [comment]
I made a PR today to fix this issue:
https://github.com/AndrewRedican/react-json-editor-ajrm/pull/193

Waiting for someone who can approve it.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
