### ISSUE TITLE
Font of the Editor

### ISSUE THREAD

**Issue by mrovinsky** [AndrewRedican/react-json-editor-ajrm#15]
Is it possible to change the font of the editor (size, family, letter spacing and so on)?

**Comment by AndrewRedican** [comment]
@mrovinsky 

Yes, you can edit any styles including font-related ones in this component. 
I've editted the original example provided in this repo, with some changes related to fonts.

In the code below, I've used the **style** property to change the font-related styles for **errorMessage**. You can read more about the **style** and other properties [here](https://github.com/AndrewRedican/react-json-editor-ajrm#component-properties).

![](https://i.imgur.com/RCVIdIl.png)

```
     <div style = {{ maxWidth: '1400px', maxHeight: '100%' }} >
         <JSONInput
             id          = 'unique_string' //an id is required
             placeholder = {sampleData}    //data to display
             theme       = 'light_mitsuketa_tribute'
             colors      = {{
                  string : '#DAA520' 
             }}
             height      = '550px'
             style       = {{
                  errorMessage : {
                      fontSize    : '20px',
                      fontWieight : 800
                  }
              }}
          />
     </div>
```

I hope this answers your question.
