### ISSUE TITLE
OnPaste Issue (large json roughly takes 25 secs and)

### ISSUE THREAD

**Issue by faizan-tariq** [AndrewRedican/react-json-editor-ajrm#152]
```
onPaste={(event: any) => {
        alert("onPaste");
}}

```
I have add this in JSONInput, but this event is not firing up. I want to minifiy the JSON onPaste to improve performance. I have seen a behavior in this library that I provide large json (not pre-formatted) then it quickly formats it and display it on the UI but If i provide pre-formarted json then it takes around 25secs to load and update the component. 

So in order to improve performance i have to override onPaste and minify json. Can you please help me how can i make onPaste work. Right now i am not getting a callback.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

There is a known limitation to the amount of data that can be analyzed and rendered in the browser. You will have to limit the amount of data given to the component. This will be addressed in the rewrite.
