### ISSUE TITLE
E notation for number issue

### ISSUE THREAD

**Issue by wwitekk** [AndrewRedican/react-json-editor-ajrm#153]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.13
2. What operating system and processor architecture are you using? *REQUIRED
MacOS
3. What did you do? *REQUIRED
Tried to use E notation for number: {test: 5.123E+7}.  (tried also: 5.123E7 and 5.123E-7)
4. What did you expect to see? *REQUIRED
No errors
5. What did you see instead? *REQUIRED
Error: Strings must be wrapped by quotes at line 2

Is there any way not to fire uo this error when using E notation for numbers?

Regards

Witold

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
