### ISSUE TITLE
Support validation using e.g. Ajv

### ISSUE THREAD

**Issue by cha0s** [AndrewRedican/react-json-editor-ajrm#154]
It would be awesome to be able to plug in something like https://ajv.js.org/#getting-started to enhance the editor with not only syntax validation, but schema validation for structured JSON.

**Comment by AndrewRedican** [comment]
Brilliant idea!

I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
