### ISSUE TITLE
When used as a controlled component, updating the document causes the caret to jump to the top left instead of where I was editing

### ISSUE THREAD

**Issue by cha0s** [AndrewRedican/react-json-editor-ajrm#155]
1. 2.5.13
2. Linux x86_64
3. Edited content
4. Caret should maintain position
5. Caret jumped to the first position in the editor

I suppose that maybe this is actually a feature request. A prop to specify caret position in the document, which would also be controlled like the document itself?

**Comment by jmaferreira** [comment]
I don't think this is a feature request. I believe its a bug.
The component can only be used as a viewer, not am editor. Copy and paste also breaks the content. The component is unusable as an editor. 

Unless we are doing something wrong.

**Comment by yashvekaria** [comment]
On copy paste JSON in editor, it gives me undefined as its values.

**Comment by cha0s** [comment]
@yashvekaria I think you should create another issue. This issue isn't about copy/paste.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
