### ISSUE TITLE
Incorrect parsing of "<", ">" symbols

### ISSUE THREAD

**Issue by eemorozov** [AndrewRedican/react-json-editor-ajrm#156]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
2.5.13
2. What operating system and processor architecture are you using? 
Windows 10 + [cloud codesandbox](https://codesandbox.io/s/affectionate-roentgen-coz2l)
3. What did you do? 

4. What did you expect to see?
Try to parse JSON that contains "<", ">" symbols
`{
 "test": "package<a>link</a>"
}
`
5. What did you see instead?
Have the wrong result in JSON editor
`{
 "test": link"
" depth="0" style="color:#CE8453">"package<a>link</a>"
}`

**Comment by eemorozov** [comment]
PR added [https://github.com/AndrewRedican/react-json-editor-ajrm/pull/158](https://github.com/AndrewRedican/react-json-editor-ajrm/pull/158)

**Comment by nageshwari17** [comment]
Hi , When will this deploy ?

**Comment by nageshwari17** [comment]
PR #158 is just replacing <a>link</a> entire stm is should not happen it
