### ISSUE TITLE
Pasted JSON throws error in Chrome

### ISSUE THREAD

**Issue by eemorozov** [AndrewRedican/react-json-editor-ajrm#157]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.13

2. What operating system and processor architecture are you using?
Windows 10 + [cloud codesandbox](https://codesandbox.io/s/affectionate-roentgen-coz2l)

3. What did you do?
Insert valid JSON in the editor in Chrome browser 
`{
 "test": "test"
}`

4. What did you expect to see?
Expect to see parsed JSON without errors

5. What did you see instead?
See error "Non-alphanumeric token '' is not allowed outside string notation at line 1".
Error is shown only in Chrome (Firefox works well) and only on paste event.
I found that after paste event Firefox has <br /> in childNodes and Chrome doesn't.

**Comment by wwitekk** [comment]
More info on this in: https://github.com/AndrewRedican/react-json-editor-ajrm/issues/149

**Comment by sOoN92** [comment]
I made a PR today to fix this issue:
https://github.com/AndrewRedican/react-json-editor-ajrm/pull/193

Waiting for someone who can approve it.
