### ISSUE TITLE
Paste is prevented when using React Portals (new window)

### ISSUE THREAD

**Issue by mpeula** [AndrewRedican/react-json-editor-ajrm#159]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
> 2.5.13

2. What operating system and processor architecture are you using? *REQUIRED
> Windows 10 Pro 64 bits

3. What did you do? *REQUIRED
> I pasted a piece of json in one line.

4. What did you expect to see? *REQUIRED
> The content added to the json

5. What did you see instead? *REQUIRED
> No content has been added to the json

6. Summary

The project I'm working on uses this component inside a [React Portal](https://reactjs.org/docs/portals.html), portals can be created inside the same document, but there are ways to create portals in[ new browser windows](https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202).

I have detected that the piece of code that is causing this issue is [this one](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/src/index.js#L570-L572), and looks like:
```javascript
onPaste(event){
    if (this.props.viewOnly) {
        this.stopEvent(event);
    } else {
        event.preventDefault();
        var text = event.clipboardData.getData('text/plain');
        document.execCommand('insertText', false, text);
    }
    this.update();
}
```
The problem is that the document is refering to is no longer the document when the component is placed, that's why it does not do anything at all.

I have modified my local library and it's working fine with this code:
```javascript
onPaste(event){
    if (this.props.viewOnly) {
        this.stopEvent(event);
    }
     this.update();
}
```

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
