### ISSUE TITLE
Update on change placeholder

### ISSUE THREAD

**Issue by mrovinsky** [AndrewRedican/react-json-editor-ajrm#16]
I use JSONInput viewOnly. Updating placeholder prop does not change the editor content.

**Comment by AndrewRedican** [comment]
Hi @mrovinsky,

I need more information than that. I cannot reproduce the issue.

Are you using the latest version of RJEA? (Should be `2.4.4` at the moment).

**Comment by mrovinsky** [comment]
Andrew,
The problem is gone after upgrading from 2.4.2 to 2.4.4 .
Thank you and sorry for the inconvenience.

**Comment by AndrewRedican** [comment]
No worries!
