### ISSUE TITLE
The comma at the end of root object caused editor to hang.

### ISSUE THREAD

**Issue by atompie** [AndrewRedican/react-json-editor-ajrm#165]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
react-json-editor-ajrm@2.5.13

2. What operating system and processor architecture are you using?
Ubuntu 20.04

3. What did you do? 
Typed inside editor {},  
The comma at the end of root object caused editor to hang.

4. What did you expect to see? 
Regular error message.
5. What did you see instead? 
The comma at the end caused editor to hang the browser. (This happens in Firefox, Chrome works fine)

**Comment by atompie** [comment]
Have anyone tested this?

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
