### ISSUE TITLE
no locale available in typescript, cannot be used

### ISSUE THREAD

**Issue by kristijorgji** [AndrewRedican/react-json-editor-ajrm#178]
Package.json
```
"react-json-editor-ajrm": "^2.5.13",
"@types/react-json-editor-ajrm": "^2.5.1",
```

Usage
```
import React from 'react';
import JSONInput from 'react-json-editor-ajrm';
import locale from 'react-json-editor-ajrm/locale/en'; // this does not exist in typescript, compilation fails 

export interface Props {
    data: Record<string, unknown>;
    onSaveClick: () => void;
}

export default function Configs(p: Props): React.ReactElement<Props> {
    return (
        <div>
            <JSONInput id="a_unique_id" placeholder={{}} theme={'darktheme'} locale={locale} height="550px" />
        </div>
    );
}

```

```
TS7016: Could not find a declaration file for module 'react-json-editor-ajrm/locale/en'. 
```

**Comment by khatran79** [comment]
Got the same issue. Any luck please?

**Comment by eszczepan** [comment]
Same issue: `Could not find a declaration file for module 'react-json-editor-ajrm/locale/en'`

**Comment by dsalgador** [comment]
Same problem here.

```
"react-json-editor-ajrm": "^2.5.13",
"@types/react-json-editor-ajrm": "^2.5.2",
```
![image](https://user-images.githubusercontent.com/33105574/133571906-bc556612-8dac-49b1-ade8-13675912663e.png)

**Comment by kelokchan** [comment]
You can do `declare module 'react-json-editor-ajrm/locale/en';` to declare the types

**Comment by darocam73** [comment]
inside `@types/react-json-editor-ajrm/index.d.ts` you can declare the module like this:

`declare module 'react-json-editor-ajrm/locale/en' {
  export default JSONInputProperties
}`

**Comment by ornakash** [comment]
Is there a fix for this without changing the @types/react-json-editor-ajrm/index.d.ts?

**Comment by yoyos** [comment]
thanks for the trick [dsalgador](https://github.com/dsalgador)

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
