### ISSUE TITLE
Add Full-Width / Full-Height support

### ISSUE THREAD

**Issue by alexahn917** [AndrewRedican/react-json-editor-ajrm#18]
Would it be possible to add a support for full-width & full-height to fit the container component (100%) of the rendered JSONInput component?

I think that it would be much more useful if dynamic sizing is enabled, if possible.

Thanks!

**Comment by AndrewRedican** [comment]
Sure thing!

**Comment by PatrickSachs** [comment]
I am using the following `style` settings for a full width editor.
```jsx
style={{
  container: {
    width: "100%"
  },
  body: {
    width: undefined,
    display: "flex"
  },
  outerBox: {
    width: "100%"
  },
  contentBox: {
    width: undefined,
    flex: 1
  },
  warningBox: {
    width: "100%"
  },
}}
```

The editor itself is wrapped in this div:
 ```jsx
<div style={{ maxWidth: '1400px', maxHeight: '100%' }}>
  {/**/}
</div>
```

**Comment by AndrewRedican** [comment]
@alexahn917, this has been fixed since version `2.4.8`
@PatrickSachs, I used some of your css to provide a built-in solution. Many thanks.

**Comment by xstable** [comment]
Works good, thanks for that. But the horizontal scroll-bar is missing if text is longer than the div-width: 
![image](https://user-images.githubusercontent.com/1778068/110950557-472bce00-8344-11eb-937e-d0aee80a1965.png)

**Comment by arthurdjn** [comment]
You can add the following style to have an horizontal scroll bar: 

```javascript
<JSONInput
  style={{
      body: {
          display: "flex",
          flexWrap: "nowrap",
          overflowX: "auto",
      },
      contentBox: {
          flex: "0 0 auto"
      },
  }}
/>
```

![image](https://user-images.githubusercontent.com/48992917/124903405-76410c00-dfd3-11eb-9ee9-81eaacf854b5.png)
