### ISSUE TITLE
JSON Editor lagging while clearing long json from the editor

### ISSUE THREAD

**Issue by aroraShru** [AndrewRedican/react-json-editor-ajrm#185]
1. What version of RJEA are you using (react-json-editor-ajrm version)?  2.5.13
2. What operating system and processor architecture are you using? Windows 10
3. What did you do? JSON Editor is being used to display a long ~700 line JSON. The usecase is to select the full json, remove it and paste a new json.  The JSON was selected and backspace was pressed to remove the JSON from json-editor.
While removing the json, the json-editor is lagging. Its getting stuck for abut ~40 secs just to remove the json from editor
4. What did you expect to see?  Expected clearing the JSON from Json-editor to be fast 
5. What did you see instead?  While clearing the JSON from editor, saw the lag of approx 40 seconds. attached the json I used for testing
[LongJson.txt](https://github.com/AndrewRedican/react-json-editor-ajrm/files/7072053/LongJson.txt)

**Comment by k4st0r42** [comment]
Same issue on same version

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

There is a known limitation to the amount of data that can be analyzed and rendered in the browser. You will have to limit the amount of data given to the component. This will be addressed in the rewrite.
