### ISSUE TITLE
string ending with backslash gives error

### ISSUE THREAD

**Issue by merlich9** [AndrewRedican/react-json-editor-ajrm#188]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.13
2. What operating system and processor architecture are you using? Windows 10 x64
3. What did you do? string that ends with escaped backslash fails.  i.e. { 'test': 'abc\\def\\' }
4. What did you expect to see? is valid json
5. What did you see instead? the trailing '\\' displays an error.  If it is removed, error goes away.  'abc\\def' shows correct, but 'abc\\def\\' shows an error even though it is valid json.

**Comment by abischolz** [comment]
Similar issue using punctuation 

1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.9
2. What operating system and processor architecture are you using? macOS BigSur 1.1 GHz Quad-Core Intel Core i5
3. What did you do? Trying to display value with lots of punctuation, but is valid JSON ("title": "Punctuation Accepted *!.,;'\"&'")
4. What did you expect to see? JSON displayed in the editor 
5. What did you see instead? Editor is escaping after '\'. Does not display the rest of the JSON (see attached) and can't edit and save. Not throwing any errors.
<img width="542" alt="Screen Shot 2021-10-20 at 1 40 16 PM" src="https://user-images.githubusercontent.com/75282566/138143862-6c4bdc4b-421d-48cb-95b4-ca6845dd2847.png">

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
