### ISSUE TITLE
HTML is removed from valid JSON strings

### ISSUE THREAD

**Issue by darrencrossley** [AndrewRedican/react-json-editor-ajrm#19]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.4.4
2. What operating system and processor architecture are you using?
chrome 65
3. What did you do?
type `<div>` into a string in the editor
4. What did you expect to see?
the text `'<div>'` entered as a valid json string
5. What did you see instead?
a new line in the editor

**Comment by duart38** [comment]
same issue here.

**Comment by AndrewRedican** [comment]
Thanks guys. I had not imagined this use case while coding logic for component.
There is definitely a bug there. I will work on it this weekend.

Thanks.

**Comment by AndrewRedican** [comment]
Hey @darrencrossley, @duart38,

This issue where html tags were removed by component has been fixed on the latest RJEA version `2.4.6`
