### ISSUE TITLE
Setting/Overwriting font size dosen't work 

### ISSUE THREAD

**Issue by krvns** [AndrewRedican/react-json-editor-ajrm#191]
1. RJEA ^2.5.13
2. Windows/Mac/Linux
3. Changing Font Size

```
<JSONInput
  id="1"
  placeholder={myJsonObj}
  locale={locale}
  width="100%"
  style={{ fontSize: 50 }}
/>
```
expected behavior: font size is set from `style` property

**Comment by kelokchan** [comment]
The correct way should be `style={{
                body: {
                  fontSize: '12px',
                },
              }}`

**Comment by krvns** [comment]
Thanks
