### ISSUE TITLE
Editor wrong parsing string with backslash and quote

### ISSUE THREAD

**Issue by zakariametal** [AndrewRedican/react-json-editor-ajrm#195]
1. What version of RJEA are you using (react-json-editor-ajrm version)?  
**2.5.13**
2. What operating system and processor architecture are you using?  
**Linux, AWS EC2**
3. What did you do?
Try to parse this string
`\"\\\"lorem ipsum dolor sit amet\\\"\"`
4. What did you expect to see? *REQUIRED
`"\"lorem ipsum dolor sit amet\""`
5. What did you see instead? *REQUIRED
`"\"`

**Comment by gudapraveenkumar** [comment]
Even I have same problem, for example I was trying to render this simple `{test:"[{\"a\":\"abc\",\"d\":\"edf\",\"c\":1}]"}` and I get this in the editor
<img width="547" alt="Screenshot 2021-11-24 at 17 15 29" src="https://user-images.githubusercontent.com/33131034/143275127-18516e41-8963-4141-a2ad-a9f280b04715.png">

**Comment by SoniaComp** [comment]
I have the same issue! I will check the code and make a PR for this issue.

**Comment by shallinta** [comment]
have the same issue

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
