### ISSUE TITLE
Bug/Issue related pasting larger JSON object

### ISSUE THREAD

**Issue by waleedasad** [AndrewRedican/react-json-editor-ajrm#20]
I found a issue that if we paste a longer format JSON object it gives random syntax error on some line whereas it is a valid JSON object. Also by pasting a larger JSON object the editor seems to be laggy

**Comment by AndrewRedican** [comment]
Hi waleedasad,

Thanks for your input. Can you expand a little bit on your first sentence? Regardless of whether it is a large input or not, there is likely a reason for finding an error, whether it be some logic missing in the component or an invalid character. I would suggest you to try to find the smallest example where this happens so I can have something to work with.

In regards to lagg on particularly large JSON objects, this is a known limitation. The lag comes from the browser attempting to render a lot of elements into the DOM. See, for each color-coded text in the RJEA component there is a span element. Any modern browser, including Chrome will struggle to render that much elements.  See here https://github.com/AndrewRedican/react-json-editor-ajrm/issues/7. I suspect that is the reason why some features, say Firebase Database, will limit the nodes or interactivity they have after a certain amount of nodes. I've thought of a way to partially show the JS Object to reduce the toll on the browser. Though, this is still work in progress, and will take some time to accomplish.
I would suggest breaking down the JS object you are either pasting or sending through the placeholder property.

**Comment by maynir** [comment]
Hi, I'm experiencing the same problem when I put in a JSON like this: "{a: 1}{".
I think the problem is with the second open "{".
The error I'm experiencing is "Uncaught TypeError: Cannot read property 'string' of undefined".

Would really like your help.

**Comment by AndrewRedican** [comment]
Hey @maynir,

Can you create a new separate issue for the issue you are having. It does not seem related to this one. Also please expand on the subject so I can help out. Although, with the little information provided, `{a: 1}{` is not valid json.

Thanks
