### ISSUE TITLE
JSONInput does not handle HTML entities properly

### ISSUE THREAD

**Issue by jluxenberg** [AndrewRedican/react-json-editor-ajrm#206]
What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.13

What operating system and processor architecture are you using? 
MacOS / ARM

What did you do?
Instantiate `JSONInput` with an object having an HTML entity e.g. `&amp;` like this:
```
import JSONInput from "react-json-editor-ajrm";
import locale from "react-json-editor-ajrm/locale/en";

export default function App() {
  const sampleObject = {
    a: "&amp;"
  };
  return (
    <div className="App">
      <JSONInput
        id="a_unique_id"
        placeholder={sampleObject}
        locale={locale}
        height="550px"
      />
    </div>
  );
}
```

What did you expect to see? 

I expect to see a JSON editor with the following object:
```
{
  a: '&amp;'
}
```

What did you see instead?

Instead, I see a JSON editor that looks like this
```
{
  a: '&'
}
```

Here's a CodeSandbox and a screenshot of the output I'm seeing:
https://codesandbox.io/s/withered-water-lww2ik?file=/src/App.js

![CleanShot 2022-03-23 at 15 48 21](https://user-images.githubusercontent.com/450478/159809089-01d7196c-edea-4681-96da-225a0868d9fe.png)

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
