### ISSUE TITLE
Giving error msg for Windows platform after pasting JSON

### ISSUE THREAD

**Issue by nahidshahin** [AndrewRedican/react-json-editor-ajrm#207]
react-json-editor-ajrm version: 2.5.13
operating system and processor architecture: Windows 10 64bit
I pasted a valid json in the editor
expected: No validation error
actually: getting validation error `Non-alphanumeric token '' is not allowed outside string notation at line 1`

Workaround: if I hit any key in the keyboard like putting an extra space resolve the error.

![error](https://user-images.githubusercontent.com/1224995/160446635-07aa5be7-591b-4e3f-9ba5-33591a7c1b56.jpg)

You can test the error here also : https://codesandbox.io/s/7ojpy3x240

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
