### ISSUE TITLE
Error message should not contain line number when not provided

### ISSUE THREAD

**Issue by IdoWeitzman** [AndrewRedican/react-json-editor-ajrm#208]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.3
2. What operating system and processor architecture are you using? Mac 64bit
3. What did you do? supplied `error` prop without the optional line property. for example `error={{ reason: 'some-error' }}`
4. What did you expect to see? error message of this structure: `some-error`
5. What did you see instead? `some-error at line undefined`

since `error.line` is optional (according to the docs), if it's not provided the error message shouldn't indicate line number.
reference in code: https://github.com/AndrewRedican/react-json-editor-ajrm/blob/7e9b63353e9148dd425bef9952e66698f20b863a/src/locale/en.js#L2

I would love to contribute a fix if possible.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
