### ISSUE TITLE
Way to access DOM node for end to end testing

### ISSUE THREAD

**Issue by s3kamble** [AndrewRedican/react-json-editor-ajrm#213]
Need a way to access proper DOM nodes for JSON, need to check code before and after "onchange",for end-to-end testing.
Currently getting **name:John;** in 4 different spans.
Want to check the value of name before and after onchange,in end to end testing

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).
