### ISSUE TITLE
The component does not work with React 18

### ISSUE THREAD

**Issue by raymondKelly** [AndrewRedican/react-json-editor-ajrm#218]
1. What version of RJEA are you using (react-json-editor-ajrm version)? ^2.5.13
2. What operating system and processor architecture are you using? MAC 64 bit
3. What did you do? Updated the JSON to what should be an invalid state
4. What did you expect to see? An error message or indication that the JSOn was invalid
5. What did you see instead? The component did not show any indication that the JSON was invalid

It appears that with React 18 that the component may now not work. I have tried with React 16 and it does work in those cases. I can't seem to see anything that would cause the issue at first glance and I see no errors in the console.

Steps to reproduce
1. `npx create-react-app my-app-js`
2. `cd my-app-js`
3. `npm install react-json-editor-ajrm`
4. Update the App.js file to include the JSONInput component
5.`npm run build`
6.`npm run start`
7. In the browser window attempt to add broken JSON and nothing happens as far as validation is concerned

**Comment by Andrey-Varakin** [comment]
Having the exact same issue on Windows 10, 64 bit.

---------------------------------------------------------------------------------------------

`ReactDOM.render(<App />, document.querySelector("#root"));` 
The above code renders the editor in its working state, validation and all.

---------------------------------------------------------------------------------------------

```
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
The above code renders the editor, but no validation occurs when editing the JSON.

---------------------------------------------------------------------------------------------

Seems like something is breaking when using the React 18 syntax.

**Comment by deadlyicon** [comment]
Same here

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

The plan is for the rewrite to be framework agnostic. I don't intend to write a wrapper for react, it is the perfect opportunity for someone to jump in on that.
