### ISSUE TITLE
Line numbers are cut off before the end of the JSON

### ISSUE THREAD

**Issue by cjh748** [AndrewRedican/react-json-editor-ajrm#219]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
^2.5.13
3. What operating system and processor architecture are you using? 
Windows 11 - Chrome
4. What did you do? 
Rendered a large amount of data
5. What did you expect to see? 
Line numbers should match up to the number of lines of JSON
6. What did you see instead?
The line numbers are cut off before the end

![image](https://user-images.githubusercontent.com/34613515/180754547-f43e34f7-3e5c-47fc-9d81-25bdf5987b7e.png)

Code:

<JSONInput
      sx={{overflow: 'hidden'}}
      name='jsonInput'
      viewOnly
      id = 'response-body'
      placeholder = {JSON.parse(responseBody)}
      locale = { locale }
      height = 'auto'
      confirmGood={false}
      style = {{
          container: {borderRadius: '8px', width: '100%'}, 
          outerBox: {width: '100% !important', maxHeight: '359px', overflowY: 'scroll'},
      }}
/>

Thanks

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
