### ISSUE TITLE
Using number less than zero

### ISSUE THREAD

**Issue by RomainDECOSTER** [AndrewRedican/react-json-editor-ajrm#221]
Hello,

When I try to use some number less than 0, I have an error in one case :

If I initialise the placeholder with `{number: -0.1}`I can update it to `{number: -0.2}` but if I initialise with `{number: 0.1}` then I try to pass it to `{number: -0.1}` with just add `-` before my number I have an error.

I provide a video to explain what's going on : 

https://user-images.githubusercontent.com/63705433/183437220-4f16e927-c7ed-4872-a83d-95b68154750b.mov

1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.13
2. What operating system and processor architecture are you using? OSX
3. What did you do? Try to put a number less than 0
4. What did you expect to see? No error when I put -0.1 (for example)
5. What did you see instead? I have mustBeWrappedByQuotes error

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll make sure this is resolved in the new project.
