### ISSUE TITLE
latest version of RJEA not working with react@v18.1.0

### ISSUE THREAD

**Issue by hodasalah** [AndrewRedican/react-json-editor-ajrm#222]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2. What operating system and processor architecture are you using? *REQUIRED
3. What did you do? *REQUIRED
4. What did you expect to see? *REQUIRED
5. What did you see instead? *REQUIRED

**Comment by hodasalah** [comment]
What version of RJEA are you using (react-json-editor-ajrm version)? latest
What operating system and processor architecture are you using? windows
What did you do? `import JSONInput from "react-json-editor-ajrm"
import locale from "react-json-editor-ajrm/locale/en"
<JSONInput id="a_unique_id" placeholder={{ "foo": "bar" }} onChange={(v) => console.log(v.plainText)} locale={locale} />
`
json appears but nothing else 
onChange doesn't fired so no value in console log
errors alert doesn't appears so you just see json in formatting

**Comment by mjrlgue** [comment]
same issue

**Comment by GoldfishPi** [comment]
Same here

**Comment by DebbieL** [comment]
same here, any solutions??

**Comment by norbertFeron** [comment]
I got the same project on my project, but the example provided (example/create-react-app-project) is working after an upgrade to react v18, but this warning came up: 
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot`

[https://reactjs.org/link/switch-to-createroot](url)

**Comment by braco** [comment]
@AndrewRedican please mark this as abandoned in npm if it's not going to be updated / pull requests accepted. Just wasted an hour figuring this out

**Comment by samdhanalakota** [comment]
@AndrewRedican Is there any work going to fix this issue?

**Comment by chandlervdw** [comment]
bummer that this seems a bit abandoned

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

The plan is for the rewrite to be framework agnostic. I don't intend to write a wrapper for react, it is the perfect opportunity for someone to jump in on that.
