### ISSUE TITLE
Issue with entering large payload

### ISSUE THREAD

**Issue by MrArun005** [AndrewRedican/react-json-editor-ajrm#229]
when I try to paste the large payload am getting the page is unresponsive and UI won't work for 5 to 10 minutes. 
![image](https://user-images.githubusercontent.com/62166323/205586855-e1c23239-0c2e-4501-a382-9ac299a17440.png)
Help me out to overcome this situation!

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

There is a known limitation to the amount of data that can be analyzed and rendered in the browser. You will have to limit the amount of data given to the component. This will be addressed in the rewrite.
