### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by PatrickSachs** [AndrewRedican/react-json-editor-ajrm#23]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
2.4.7
2. What operating system and processor architecture are you using? 
Windows 10, Intel 64 bit
3. What did you do?
Use the editor 🙃
4. What did you expect to see?
I was hoping for a locale/translation system.
5. What did you see instead?
Hardcoded error messages.

While not critical at the current time for my use case a way to translate error messages into different languages would be an important addition to the editor.
I don't think the editor should come with dozens of languages built in, but adding prop which allows you to pass a locale object containing different error messages would be awesome.

**Comment by AndrewRedican** [comment]
This is a great suggestion.

Any particular languages you'd be interested in having support for?

**Comment by Patrick-Sachs** [comment]
My main requirement in english & german. Although I think that designing an open system with user customizable strings would be best.

**Comment by AndrewRedican** [comment]
I've added `modifyErrorText` property to give the developer access to modify the error or warning message.
I will be working on built-in solutions for localization in the next few weeks.

**Comment by AndrewRedican** [comment]
@PatrickSachs for your contribution!

This is available as of version `react-json-editor-ajrm@2.5.0`
