### ISSUE TITLE
BREAKPOINTS IN ARRAYS 

### ISSUE THREAD

**Issue by FlorBordenave1** [AndrewRedican/react-json-editor-ajrm#232]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
     - 2.5.13
2. What operating system and processor architecture are you using? 
  
3. What did you do? 

I did this object 

```
export const ModelJson = ({
    data,
}: ModelJsonProps) => {
    return (
        <JSONInput
            placeholder={data}
            height='100%'
            width='100%'
            colors={{ background: '#434343', number: '#fff', string: '#fff', keys: '#fff', primitive: '#fff', colon: '#fff' }}
        />
    );
}
```
4. What did you expect to see? 
    - Inside the JSON object I have an array and I want it to look like this, 
    
![image](https://user-images.githubusercontent.com/86444867/206552102-ebdf6e7d-fb2f-4b0c-8c83-7e78784fb7c4.png)
 inputs: [    0.43, 0.43, 0.43 ,0, 0.43 ]
    instead of this:
     inputs: [    
      0.43,
      0.43, 
      0.43 ,
      0, 
      0.43 
    ]

5. What did you see instead?
How can I prevent these` <br>` and `&nbsp;&nbsp;&nbsp;&nbsp; `?

![image](https://user-images.githubusercontent.com/86444867/206553008-7399e13a-ff8e-49d1-b4ae-8a576783f15f.png)

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
