### ISSUE TITLE
Undo/Redo Does Not Work

### ISSUE THREAD

**Issue by abirmingham** [AndrewRedican/react-json-editor-ajrm#233]
1. What version of RJEA are you using (react-json-editor-ajrm version)? _2.5.13_
2. What operating system and processor architecture are you using? _Windows x86_
3. What did you do? _Type text into editor, wait >1 second, press ctrl+z (or select "undo" in right click menu)_
4. What did you expect to see? _Undo occurs_
5. What did you see instead? _Nothing occurs_

Note that undo/redo does function as expected if invoked within `waitAfterKeyPress` milliseconds.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite.
I'd like to thank you for using and taking interest in this project.

I'd like to apologize for not following up sooner. However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).
