### ISSUE TITLE
make width adabtable

### ISSUE THREAD

**Issue by quorak** [AndrewRedican/react-json-editor-ajrm#24]
hey there,

thanks for this great component. We need to have the width adapting to the surrounding component. Can we support `width="100%"` ? right now it just uses `100px` instead

**Comment by AndrewRedican** [comment]
Hey @quorak,

I'll be adding support for percentages to `width` and `height` shorthand component properties.

In the meantime, you can also use the `style` property. See @PatrickSachs' solution to a similar question here https://github.com/AndrewRedican/react-json-editor-ajrm/issues/18.

**Comment by AndrewRedican** [comment]
I will be closing this issue in favor of this one: https://github.com/AndrewRedican/react-json-editor-ajrm/issues/18
