### ISSUE TITLE
On Enter Key Pressed, incorrect editor behavior

### ISSUE THREAD

**Issue by JustPilz** [AndrewRedican/react-json-editor-ajrm#25]
Latest react-json-editor-ajrm version (2.4.8)
I have a strange behavior with simple object: 
`{
    key: "123"
}`
When I tried to add new key and value, json-editor removed it. Also symbol «}» has been removed when I tried to fix syntax error:
![react-json-editor-ajrm](https://user-images.githubusercontent.com/24465747/43142697-a84f1c0c-8f61-11e8-955a-be36e90341b0.gif)

**Comment by AndrewRedican** [comment]
@JustPilz,

Thanks. Your screenshsot is extremely helpful. I am renaming this issue with a more specific description.

**Comment by AndrewRedican** [comment]
Pressing enter creates a DIV node inside this contentEditable component. DIV nodes were not accounted for in component logic. I am surprised we had not come across this earlier. I am submitting a fix right now.

Thanks for trying this project. Great find. Thanks again ^_^

**Comment by AndrewRedican** [comment]
@JustPilz, this issue has been fixed in the latest `react-json-editor-ajrm@2.4.9`
