### ISSUE TITLE
messageWidth is not defined

### ISSUE THREAD

**Issue by KinTsang** [AndrewRedican/react-json-editor-ajrm#3]
Hi Andrew!

I am currently using the latest release 2.0.3 and when I am entering an invalid JSON, the error message does not appear on top of the editor and it is console logging out an error `messageWidth is not defined`

Thanks!
Kin

**Comment by AndrewRedican** [comment]
Hi KinTsang.

This has been fixed since version `2.1.5`. You can run `npm i react-json-editor-ajrm@latest` to pull the latest version into your project.
