### ISSUE TITLE
🌍 🌎 🌏 Localization Support: Translators Needed

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#30]
We have come up with a list of languages we'd like to support. As explained in the main documentation, this component enables users to validate correct syntax for javascript data structures. We are hoping we can extend this component's usefulness by providing locale support to non-english speakers.

We hope to accomplish this goal by crowdsourcing this task to kind volunteers around the globe.

For now, this task for any language is relatively small. About 20 to 30 small lines that need to be translated.

| Name   | Status | Contributor(s) |
| ------ |-------------| ----- |
| Chinese      |  Done | @ADirtyCat |
| Spanish      |  Done | @AndrewRedican |
| English       |  Done | @AndrewRedican |
| Hindi          |  Done | @shehbazjafri |
| Tamil         | Done | @vasind |
| Indonesian |  Done | @radityasurya |
| Russian      |  Done  | @askesis |
| Polish         |  Not Started  | |
| French        |  Done | @cbonaudo |
| Hungarian  |  Not Started | |
| Japanese    |  Done | @Adityaperiwal |
| Portuguese |  Done | @AllanKDeveloper |
| German      |  Done | @PatrickSachs  |
| Italian         | Not Started |  |

Can't find your native language listed here? How about becoming a contributor yourself?
Below you'll find some instructions to help you get started.

### Getting Started

0. Sign in to Github.

1. Fork this repository.

2. [Optional] Clone your forked repositiory and use your code editor of choice (if you know what you are doing).

3. Create a new branch.

4. Go to the `locale` folder. The path should look something like this: `https://github.com/YourUsername/react-json-editor-ajrm/tree/the-branch-name/src/locale`

5. Create a new file for the languange you are translating for. Please use the two letter abbreviation for languages listed on here [ISO 639](http://www.loc.gov/standards/iso639-2/php/code_list.php) and three letter abbreviation for those that do not have the latter. <img src=https://i.imgur.com/S1oLXiG.png>

6. You can copy the contents from any other file in this directory of a language you are familiar with and begin translating.

7. When you are finished, kindly send us a pull-request. Please include the name of the language you have translated for, and any questions or issues you might come across.

### Some useful links below:
+ [About Forking](https://guides.github.com/activities/forking/)
+ [More on Social Coding](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

We welcome contributions of any kind, and make sure we acknowledge these contributions! By contributing, you will also feature in our documentation's footer contributors section.

Thanks!

**Comment by AndrewRedican** [comment]
Hey @AllanKDeveloper, I am reaching out to you to see if we can get a hand.

We've added some additional terms to the locale system in the latest PR. We've translated a few terms already but we might your need expertise. Let me know if you have time to check and update.

**Comment by AllanKDeveloper** [comment]
Hi, @AndrewRedican I already created the pull request.

**Comment by ADirtyCat** [comment]
Hi, @AndrewRedican  I already created the pull request.
