### ISSUE TITLE
Upon paste of content from clipboard, html markup is filtered out

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#34]
1. What version of RJEA are you using (react-json-editor-ajrm version)? `2.5.1`
2. What operating system and processor architecture are you using? `Windows 10`
3. What did you do? 
4. What did you expect to see?
5. What did you see instead? When pasting, html dissapears. Only text is pasted.

Preliminary examination shows that tags never actually get pasted into component.
Meaning, component logic itself is not removing these tags unexpectedly.

Could it be a browser / react / contentEditable built-in security measure?
I will check on clipboard and paste configuration.

**Comment by AndrewRedican** [comment]
Moving discussion from https://github.com/AndrewRedican/react-json-editor-ajrm/issues/32 to here.
Adding @joe-at-startupmedia to conversation.

**Comment by martamius** [comment]
I have fixed this issue in pr #98.
