### ISSUE TITLE
Error parsing booleans when using Copy/Paste

### ISSUE THREAD

**Issue by KinTsang** [AndrewRedican/react-json-editor-ajrm#4]
Hi Andrew,

There seems to be an error when paring boolean property values.

When I copy and paste in the following object:
`{ 
 "array": [],
 "propertyBoolean": false
}  
`
It throws an error 'String must be wrapped in quotes at line 3.'

but then when I follow the instruction to wrap it in quotes:
`{ 
 "array": [],
 "propertyBoolean": 'false' 
}  
`

I get the error 'primitives can only follow '['':'',' tokens at line 3.

Thanks!

**Comment by AndrewRedican** [comment]
Thanks for the feedback, I should be able to fix it during the weekend in version `2.1.8`.

**Comment by AndrewRedican** [comment]
This has been fixed.
