### ISSUE TITLE
Tabs result in focus change

### ISSUE THREAD

**Issue by ankitr** [AndrewRedican/react-json-editor-ajrm#42]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.3
2. What operating system and processor architecture are you using?
Mac OSX 10.13.1 on 2.3 GHz Intel Core i5
3. What did you do?
Press tab within the editor
4. What did you expect to see?
2 or 4 spaces
5. What did you see instead?
The focus changed from the editor to another element on the page

**Comment by PatrickSachs** [comment]
Hallo @ankitr 

Thank you for reporting this!

I was able to reproduce the issue on my end. This should hopefully be a quick fix.

**Comment by PatrickSachs** [comment]
A fix for this has been merged. 

However, it may take some time before being published to NPM.

**Comment by ankitr** [comment]
Thanks a bunch! Excited for the publish.
