### ISSUE TITLE
How do you set an initial content/value?

### ISSUE THREAD

**Issue by rodrigofd** [AndrewRedican/react-json-editor-ajrm#45]

**Comment by PatrickSachs** [comment]
Hey @rodrigofd 

The initial value can be set using the `placeholder` prop. 

Should the value passed into placeholder ever change, the value will be reset to the value passed, so it essentially functions like a value prop.

If you need an example on how to use take a look at `/example/index.js`.

**Comment by rodrigofd** [comment]
Awesome, thanks for the quick help! :) Great job with this component

**Comment by DominicTobias** [comment]
Hm it doesn't seem to work for updates - e.g. I have a Reset button which modifies that value and re-renders but the component does not update its contents
