### ISSUE TITLE
Format Unexpectedly Changes On Specific Syntax Error

### ISSUE THREAD

**Issue by giorgi-m** [AndrewRedican/react-json-editor-ajrm#46]
1. version 2.5.3
2. OS: ubuntu

Below is a screenshot of correct JSON displayed

![screenshot from 2018-08-27 10-58-12](https://user-images.githubusercontent.com/41240312/44645349-62ce6380-a9e8-11e8-9597-14df584d026d.png)
Then imagine I make syntax error, say on line 11 I just typed symbol s.
Below is what suddenly happens to the display:

![screenshot from 2018-08-27 10-58-54](https://user-images.githubusercontent.com/41240312/44645381-7aa5e780-a9e8-11e8-87d1-effd74b0e851.png)

Why?

**Comment by AndrewRedican** [comment]
Hey @giorgi-m,

Can you include the specific reproduction steps. I am unable to replicate.

As for an explanation to this formatting error, each line is not an div element on its own, instead lines are controlled by newline characters. There error involves newlines not being added. (In the near future, I intend to provide a div element for each line as part of a bigger update for collapsible nodes).

In the meantime, can you give me the exact repoduction steps please?

**Comment by giorgi-m** [comment]
Sadly I can't reproduce it either it seems.
I think I had something like below (or close to it):

```
 <JSONInput
        id="a_unique_id"
        placeholder={JSON.parse(this.state.configValue ? this.state.configValue : "{}")}
        locale={locale}
        onChange={e => {
            function isJSON(str) {
                if (typeof str !== "string") {
                  return false;
                }
                try {
                  JSON.parse(str);
                  return true;
                } catch (e) {
                  return false;
                }
              }

          if (isJSON(e.json)) {

            this.setState({
                configValue: e.json // maybe I used e.smthElse here
            });
          }
        }}
        height="550px"
      />

```
But above code seems ok on my end.
If I encounter again this error, I will try to give you full info. But error was there, hence the screenshot.

**Comment by AndrewRedican** [comment]
This issue has been fixed and is available in the latest version `react-json-editor-ajrm@2.5.4`.
