### ISSUE TITLE
Error line incorrectly reported

### ISSUE THREAD

**Issue by giorgi-m** [AndrewRedican/react-json-editor-ajrm#47]
1. version 2.5.3
2. OS: ubuntu

I suppose it wrongly reports line of error. e.g.

![screenshot from 2018-08-27 11-04-42](https://user-images.githubusercontent.com/41240312/44645669-7a5a1c00-a9e9-11e8-8daa-15b3190a7fdf.png)

You can see above it reports error is on line 17, whereas in reality the error is on line 13, where I typed symbol "r". (If I remove that "r" from line 13 and its corresponding comma then it works fine).

**Comment by EXPEakhasawneh** [comment]
Same here 
![image](https://user-images.githubusercontent.com/29892725/44649427-54298180-a9d3-11e8-91d5-56dabeff3957.png)

**Comment by AndrewRedican** [comment]
Hey @giorgi-m thanks for reporting this issue,

I'll be submitting a fix shortly.

@EXPEakhasawneh, can you please expand on your input.

**Comment by EXPEakhasawneh** [comment]
I'm limited with width dimension, the figure just to show how it looks like

**Comment by AndrewRedican** [comment]
Hey @EXPEakhasawneh I think yours is a different issue. Is this what you refer to https://github.com/AndrewRedican/react-json-editor-ajrm/issues/8? If its something else, please submit a separate issue on the provided template to keep things clean.

Also, already working on the original issue reported here.

**Comment by EXPEakhasawneh** [comment]
@AndrewRedican no its the same, thanks

**Comment by AndrewRedican** [comment]
This issue has been fixed and is available in the latest version `react-json-editor-ajrm@2.5.4`.
