### ISSUE TITLE
Enhancement request: Add JSON5 support

### ISSUE THREAD

**Issue by glenne** [AndrewRedican/react-json-editor-ajrm#48]
With growing support for [JSON5](https://json5.org/), it would be a bonus if react-json-editor-ajrm could support JSON5 as well.  The ability to add comments and other sugar is very attractive.

**Comment by AndrewRedican** [comment]
Hi @glenne,

Excellent suggestion. We have discussed the possibility of extending this component to understand other data structure syntax.

When will we start working on this?
First we need make sure this component is stable and have all the relevant features we'd like it to have. I'd say within the next three to six months, depending on time availability of contributors, we'll get started.

I just wanted to let you know we intend to add it.

Closing this issue in favor of https://github.com/AndrewRedican/react-json-editor-ajrm/issues/50. Feel free to leave addtional comments there.
