### ISSUE TITLE
On scrolling after the specified height, cursor is not visible

### ISSUE THREAD

**Issue by monicagangwar** [AndrewRedican/react-json-editor-ajrm#57]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2. What operating system and processor architecture are you using?
3. What did you do?
4. What did you expect to see?
5. What did you see instead?

**Comment by AndrewRedican** [comment]
Hey @monicagangwar,

I don't see an issue with the cursor when scrolling over the component.

By the title of this issue, I understand you are somehow telling the component to scroll from the code. This react component does not have a onScroll property to use. Perhaps you are attempting to modifying the scrollTop attribute of the DOM element directly?

I'm at a loss to know how I can help you. Can you provide more information please?

**Comment by monicagangwar** [comment]
Hey @AndrewRedican 
No, I'm not attempting scroll from the code. I have a component like this
```
 <JSONInput id='raw' placeholder={data} theme="light_mitsuketa_tribute" locale={locale} height="300px" width="100%" onChange={(event) => {this.handleChange(event, null)}}/>
```
When i scroll this component after 300px and attempt to place the cursor, it goes missing. I can edit the data and everything but cursor remains invisible

version i'm using is `"react-json-editor-ajrm": "^2.5.4",`

**Comment by AndrewRedican** [comment]
I still don't see what you mean.

Check this screen capture with the code you provided.

![screencapture](https://user-images.githubusercontent.com/24832471/45203092-39a7a180-b238-11e8-87d3-16a58a90de87.gif)

What operating system and processor architecture are you using?

Did you check any errors on the console log?

**Comment by AndrewRedican** [comment]
Hey @monicagangwar,

I am closing this issue. I have not heard from you in a while. If you continue to have issues regarding this, feel free to create a new issue.

Before you do, please be sure to read our new documentation on how to submit an issue [here](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/CONTRIBUTING.md#how-to-report-a-bug)
