### ISSUE TITLE
Error on creating a new react build

### ISSUE THREAD

**Issue by marcuscaum** [AndrewRedican/react-json-editor-ajrm#59]
![image](https://user-images.githubusercontent.com/5979318/45269091-12cab480-b45e-11e8-8ca7-0c69cd3719f7.png)

1. What version of RJEA are you using (react-json-editor-ajrm version)? `v2.5.4`
2. What operating system and processor architecture are you using?
3. What did you do? `yarn run build`
4. What did you expect to see? `a build complete`
5. What did you see instead? `an error that fails my build system`

**Comment by Patrick-Sachs** [comment]
Hey @marcuscaum,

you are importing the /es version of the code. This is not compatible with create react app. Please import the non ES version.

Please take a look at the *Hint* in the "How to Use" section in the readme. Does this solve your problem?
https://github.com/AndrewRedican/react-json-editor-ajrm#how-to-use

**Comment by marcuscaum** [comment]
Yes, solved! Thanks!
