### ISSUE TITLE
Editor cannot handle backslash

### ISSUE THREAD

**Issue by ADirtyCat** [AndrewRedican/react-json-editor-ajrm#60]
There is a backslash character in my JSON  #data.
The component cannot process this character prompt error message.
Unexpected ''yii\db\Connection'' token found at line 5

```

##############################################################
##    Unexpected ''yii\db\Connection'' token found at line 5 
##############################################################
{
  class: 'yii\db\Connection'
}
```

|Problem|Describe|
|-|-|
|version of RJEA |^2.5.4|
|operating system|Windows|
|What did you do|Formatting JSON display And edit |

**Comment by AndrewRedican** [comment]
Let me know if this was solved in the latest version `react-json-editor-ajrm@2.5.5`.

**Comment by ADirtyCat** [comment]
@AndrewRedican No, not yet. I can also see that error.

**Comment by AndrewRedican** [comment]
Waited for a timely reply. I am closing this now. 

Feel free to open an new issue should you have the same or a similar issue. See [guidelines](https://github.com/AndrewRedican/react-json-editor-ajrm/blob/master/CONTRIBUTING.md#how-to-report-a-bug).

**Comment by ADirtyCat** [comment]
Sorry , Forgot to reply you
