### ISSUE TITLE
Unpolyfilled ES6 version of component fails to build with React-Create-App

### ISSUE THREAD

**Issue by valenticanadell** [AndrewRedican/react-json-editor-ajrm#68]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
2.5.5
2. What operating system and processor architecture are you using? *REQUIRED
Macbook Pro with Visual Studio Code
3. What did you do? *REQUIRED
Used the editor in my React page, which ran perfectly with "npm run dev", but gives me error when "npm run build".
4. What did you expect to see? *REQUIRED
Not an error
5. What did you see instead? *REQUIRED
An error:

"
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-json-editor-ajrm/es/index.js:12

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! operation-react-app@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the operation-react-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
"

What did I do wrong?
<img width="722" alt="screen shot 2018-09-27 at 13 36 37" src="https://user-images.githubusercontent.com/43641090/46143489-69a3fc80-c25a-11e8-83ae-2744559ea811.png">

**Comment by AndrewRedican** [comment]
Hi @valenticanadell,

I don't have much experience with `create-react-app` itself. Unfortunately, the error gives remarkably little information. One of our contributors was kind enough to set up a project example using `create-react-app`. 

@PetrykowskiM feel free to chime in when you have time.

What I would suggest you to do is to use `react-json-editor-ajrm` instead. `react-json-editor-ajrm/es` is an unpolyfilled ES6 version of the component, which means you would use it if you are managing the transpiling/polyfilling configuration yourself.

Let me know how it goes.

**Comment by AndrewRedican** [comment]
Hey @valenticanadell,

### I got a quick reply asking in the `react-create-app` Github project.

> With Create React App 1, we expect that any modules on npm are compiled down to ES5.

> With Create React App 2 (coming out in a few days) we expect that modules on npm are using any version of JavaScript. But still expect that they don’t use custom syntax like Flow, JSX, or experimental transforms. Enabling those would make it too difficult for the whole ecosystem to adapt when these proposals change.

So there's your answer. If you are using the current version of `react-create-app` you should use `react-json-editor-ajrm` not `react-json-editor-ajrm/es`.

**Comment by valenticanadell** [comment]
OK, thank you a lot for your help!!

**Comment by valenticanadell** [comment]
Hey, we just checked, we are not using the /es version but the normal version.

<img width="415" alt="screen shot 2018-10-01 at 14 32 33" src="https://user-images.githubusercontent.com/43641090/46288689-df73d500-c586-11e8-9c8c-20c12754b020.png">

<img width="323" alt="screen shot 2018-10-01 at 14 32 19" src="https://user-images.githubusercontent.com/43641090/46288696-e4d11f80-c586-11e8-80bb-d6e6ce5ab7b0.png">

<img width="705" alt="screen shot 2018-10-01 at 14 39 53" src="https://user-images.githubusercontent.com/43641090/46288999-f4049d00-c587-11e8-99e0-9319f6d02995.png">
 But as you can see when trying to npm run build it tells me /es/.
Why?

**Comment by PatrickSachs** [comment]
If you look at the `package.json` of the `react-json-editor-ajrm` in your `node_modules` folder, you will see that it has an entry called `module` pointing to `/es/index.js`.

The module field is used to link to an ES6 version of the code. This is to be used by tools like webpack which can actually work with non commonjs modules. Tools that do not support it(like create-react-app) should ignore it. But since nothing is perfect it looks like react-scripts 1 has a bug that causes them to use this field regardless.

The fix would either be:

- Update to react-scripts 2
- Import `react-json-editor-ajrm/index explictly`

I understand that this is an inconvenience, but I don't think we should change a correct setting in the package.json to work with a tools that interprets it incorrectly.

**Comment by valenticanadell** [comment]
I tried to import react-json-editor-ajrm/index as you said, seems to compile.
Thank you very much!!
