### ISSUE TITLE
Review Code Base

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#74]
The objective behind this task is to improve in general project `maintainability`.

At the moment, main code has not changed much since the past 6 months. It was designed to provide the intended functionality first. I would like to make improvements to the code base, not to add new features but to improve project maintainability in general.

| Task | Reason | Implementation |
| :--- | :--- | :--- |
| [**Add to Documentation**]() | There are some project specifications, such as use of `for` instead of `[].forEach()` or `[].map()` in order to support IE11 without additional babel/webpack configuration. These project quirks should be documented somewhere. | Add a new page wiki to document project specifications. | 
| [**Linting**]() | Adding some very basic javascript styling rules will help improve code readability, and stability by a bit. We do not intend to enforce our own "coding style", just establish some common grounds. | Create a separate thread to propose lint rules. Discuss. Perhaps use eslint in the project. Connet EsLint to test automation. Travis Build should fail if any lint checks fail. |
| [**Sub Components**]() | At the moment, project ships as a single component. We want that to continue being the case. However, at the moment this project uses one component, thus we seem to be a bit croweded by internal methods/variables. Creating sub components will definitely improve project readability. | Create sub components for the larger components of the project (not tokens) seems to be a good starting point. |
| [**Code for Humans**]() | At this point in time, project was not written in a sense that is easy to pick up by anyone that easily, unless you are brilliant genius. Improving readabily will encourage more contribution. | Flatten logic by preventing nesting of code (perhaps use linting to help). Review variable naming. Add descriptive names for logic operations. Add comments where variable naming is not enough to explain specific things. |

**Comment by PatrickSachs** [comment]
This is a good idea. I think the "Sub Components" Task should go hand in hand with transforming the editor into a more universal editor, as both will require a large overhaul of the code base.

**Comment by AndrewRedican** [comment]
I am glad you think it is a good idea.

Initially I was thinking about separating the 'physical' sections, i.e. the `labels container` and the `warning container`, etc. But I think we also must separate the logic portion into its own directory, similar to what you did with locale support.

**Comment by weswhite** [comment]
Hey I am willing to help out a bit here. I am forking the work (thanks btw) to add some custom functionality. I could build it in as a component/feature you can toggle if you like. All that said, I am having troubles figuring out the best way to work on the package in "dev" as the example sections pull from the node_module and not the src.

**Comment by weswhite** [comment]
@AndrewRedican also if you see places you would like pulled out as components let me know and i can see what i can do

**Comment by AndrewRedican** [comment]
@weswhite absolutely.

I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).
