### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by pjanik** [AndrewRedican/react-json-editor-ajrm#77]
Any chances that there are plans to support JSON Schema validation (e.g. using https://github.com/epoberezkin/ajv)?
I can also imagine doing that by hand in `onChange` handler if I could only display my own error message somehow.

**Comment by PatrickSachs** [comment]
Hello @pjanik!

Thank you for this feature request. I don't think that JSON Schema validation should come built in with this component(seeing as we plan to "upgrade" it to a more universal syntax editor not just for JSON #50).

However I really like your idea of being able to return custom errors from e.g. onChange functions. I'll mark it as a feature request and someone will take a look at it once able.

We are also always happy to accept PRs 😉

**Comment by gnir-work** [comment]
Will this feature be merged any time soon? I would love it for my project.
