### ISSUE TITLE
Polyfill .map() and .forEach() functions to Support IE

### ISSUE THREAD

**Issue by AndrewRedican** [AndrewRedican/react-json-editor-ajrm#82]
Some time ago, we replace all forEach() with for functions to provide support for IE. Upon recent observation, .map() is also lacking support from Internet Explorer. In addition to that, new helper suites / functions `err` and `mitsuketa` use .forEach functions internally.

Because of these recent additions, and probably because `.map()` is not polyfilled it is likely that this project does not properly upport IE.

I am considering to add our own version of `forEach(array,callback)` and `map(array,callback)`. Our should we look into our project build set up to polyfill automatically?

Let me knoe what you think @PatrickSachs.

**Comment by PatrickSachs** [comment]
I think for now it's easiest if we write our own (non global) polyfills for these two functions and then import them. (Since its just two functions)

I haven't yet fully wrapped my head around automatic polyfills for libraries yet so I don't have a clear recommendation on how to set that up if we decide to go with this ultimately.

**Comment by JustFly1984** [comment]
If you build your React.js project with webpack and babel, all polyfills will be provided on build time, so you generally should not worry about providing polyfills in library.

**Comment by AndrewRedican** [comment]
IE11 will never be supported again, ever.

I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).
