### ISSUE TITLE
Review IE11 Unsupported ES6 Syntax on Project

### ISSUE THREAD

**Issue by IvanRodriCalleja** [AndrewRedican/react-json-editor-ajrm#84]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
"react-json-editor-ajrm": "^2.5.6"
2. What operating system and processor architecture are you using
Windows 10, Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

Hi,

I am using the editor and it works well on chrome but i have some problems on IE11 but i am not totally sure if is caused only by this library or some configuration of my project.

When i use the react-json-editor-ajrm and i try to use on IE11 the page is completely down, the console show me the a `Syntax error`. The syntax error, set the error in this line.

![image](https://user-images.githubusercontent.com/22966198/47496610-a95d0480-d857-11e8-8158-1c1208d62f61.png)

This is after of register the module in webpack.

I saw in your project that all the library has polifylls to support IE11, it think this is not a polifyll problem because i tried to add all possible polifyll and try and i got the same error.

If i add the library directly in my project (all files manually) it works perfect on IE11.

**My babel devDependencies:**

![image](https://user-images.githubusercontent.com/22966198/47496792-3738ef80-d858-11e8-8b28-dbdf87837d23.png)

**My babel dependencies: **
![image](https://user-images.githubusercontent.com/22966198/47496811-4881fc00-d858-11e8-81b2-0e480dfbb794.png)

**index.js**
`import '@babel/polyfill';`

**.babelrc**
![image](https://user-images.githubusercontent.com/22966198/47496891-8717b680-d858-11e8-8725-aabbf2ffb2a5.png)

**.browserlistrc**
![image](https://user-images.githubusercontent.com/22966198/47496913-9e56a400-d858-11e8-9821-892e9f0713cc.png)

Any suggestion about this error, is it possible by my babel versions?

**Comment by PatrickSachs** [comment]
Hello,

sorry for the super late reply, I was on vacation for the last few days and Andrew seems to be really busy as well.

How are you importing this component in your code? If you are currently using `react-json-editor-ajrm` try using `react-json-editor-ajrm/index`.

**Comment by IvanRodriCalleja** [comment]
Hi,

I tryed both and any of this worked for me.
I think the problem is the babel dependencies in my project but i am not totaly sure, i have to try to update all my dependencies, if It does't work, i will try to start a project from 0 to can detect the problem.

**Comment by AndrewRedican** [comment]
Sorry for the late reply as well @IvanRodriCalleja.

IE is complining most likely because it does not understand this syntax.
IE11 does not support default parameters unfortunately. See http://kangax.github.io/compat-table/es6/ for more information. We intend to provide as much support a we can for IE11, so we will have to review where we use this and/other syntax that

**Comment by AndrewRedican** [comment]
I will submit a PR for this in the next few days. Thanks.

**Comment by joshgo** [comment]
Hi @AndrewRedican, Is this issue still being worked on?

**Comment by AndrewRedican** [comment]
IE11 will no longer be supported, ever.

I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).
