### ISSUE TITLE
Cursor jumps to beginning of text input

### ISSUE THREAD

**Issue by pascal-codetaal** [AndrewRedican/react-json-editor-ajrm#88]
1. What version of RJEA are you using (react-json-editor-ajrm version)? 
2.5.8
2. What operating system and processor architecture are you using?
Mac os x
3. What did you do? 
I created an instance of the json editor and the placeholder is attached a reactive value.
 I configured the json editor with the option reset={false} so no update should happen when the placeholder value updates. 

I also created a codesandbox where you can see the problem, start editing the text and wait a little bit and the cursor will jump.

https://codesandbox.io/s/z6jmy6j8xl

4. What did you expect to see? 
I would expect the cursor keep the same position.

5. What did you see instead? 
The cursor jumps to the beginning of the input

**Comment by PatrickSachs** [comment]
Hey @pascal-codetaal 

Whenever the user stops editing the text the code will be reformatted after a certain amount of time without any further interaction. This "format" is what currently resets the cursor. I agree that this is not nice looking and rather unintuitive.

We'll look into this. Thank you for reporting this.

**Comment by pascal-codetaal** [comment]
@PatrickSachs do you have an idea how to fix this? And if so, perhaps i can help...

**Comment by AndrewRedican** [comment]
Cursor jump is one of those things I have been wanting to fix for some time.

@pascal-codetaal, you are more than happy to have you involved. Feel free to submit a PR.

**Comment by lybo** [comment]
@pascal-codetaal @AndrewRedican 

I have the same annoying issue. If it's difficult to keep the cursor to the same position then I suggest a quicker solution: 

* on `reformat` event the cursor should loss of focus from the editor (blur/focus out event). 

Because the main problem is while I'm typing and the cursor is reset then I continue writing at the beginning of the editor which causes json error :(

**Comment by lx-mn** [comment]
Facing same issue. One notable piece of information is this doesn’t happen if there is no placeholder prop passed even after formatting the json

**Comment by CrizR** [comment]
Bump, this is an issue for me too.

**Comment by CrizR** [comment]
Yeah, this is a major issue for me as well.

**Comment by vejandla** [comment]
@lx-mn How do you assign a value if you do not pass in place holder? is there a different prop for which we can assign the value to?

**Comment by vejandla** [comment]
having the same problem. sometimes our json content is 700+ lines, reformatting for every key press is really knocking down the performance of the application.

@lybo did you find any meaningful solution?

**Comment by alexxshadow** [comment]
An old thread I know.. but if anyone else stumbles across this looking for a solution then I've found the following to work (some option removed to keep it shorter, but essentially I am setting a 'keyPressed' boolean, a useEffect hook, and the 'viewOnly' option, which gets momentarily switched on and off. Not pretty, but it seems to work.

```
const Edit = ({ metadata, handleChange }) => {
	const [keyPressed, setKeyPressed] = useState(false);
	const [data, setData] = useState(false);

	useEffect(() => {
		handleChange(data);
		if (keyPressed) {
			setKeyPressed(false);
		}
	}, [keyPressed]);

	return (
		<Wrapper>
			<JSONInput
				id="editor"
				waitAfterKeyPress={0}
				placeholder={metadata}
				viewOnly={keyPressed}
				onChange={(data) => {
					setKeyPressed(true);
					setData(data);
				}}
			/>
		</Wrapper>
	);
};
```

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
