### ISSUE TITLE
Bug when Adding “>” In Double Quotes

### ISSUE THREAD

**Issue by jurmann** [AndrewRedican/react-json-editor-ajrm#91]
1. What version of RJEA are you using (react-json-editor-ajrm version)?
2.5.8
2. What operating system and processor architecture are you using?
Mac OS
3. What did you do?
Added a value of `">"` to dict (same bug is seen with `"<"`).
4. What did you expect to see?   

    ![4acff8ac-f0ee-4328-9b23-5272c8c71255](https://user-images.githubusercontent.com/23388989/48282836-0809ad00-e418-11e8-979c-127a53ba20e3.png)

5. What did you see instead?
The `">"` is being reformatted as `"" depth="0" style="color:undefined">">"`

    ![2018-11-09_11-52-33](https://user-images.githubusercontent.com/23388989/48283166-f5dc3e80-e418-11e8-87ba-18968f872adb.gif)

#### Workaround
If `>` or `<` is wrapped in single quotes this bug does not occur.

**Comment by PatrickSachs** [comment]
Thank you for reporting this and sorry for getting back at you so late.

Unfortunately Andrew and myself are rather busy at the current moment so I cannot guarantee a quick fix. But we'll get back at you once possible.

We also also always open to Pull Requests if you feel like lending a hand :+1:

**Comment by ctoppel** [comment]
This issue still persists and will force us to use another component if not fixed. Love everything else, and hope that a fix can be done for this.

**Comment by AndrewRedican** [comment]
I no longer intend to update this project. I am working instead on a complete rewrite. 

I'd like to thank you for using and taking interest in this project.

I also would like to apologize for not following up sooner.  However, do realize for the most part this has been a one-man show, and the occasional contributions I used to receive. What I am saying is, I am in dire need of volunteers. 

If this is something you would be interested in participating in, you can join in the [discussion](https://github.com/enio-ireland/enio/discussions/61).

I've taken note of this thread, and I'll keep this under consideration for the new project.
