### ISSUE TITLE
How to install successful in React + Typescript

### ISSUE THREAD

**Issue by lvybriage** [AndrewRedican/react-json-editor-ajrm#94]
1. What version of RJEA are you using (react-json-editor-ajrm version)? *REQUIRED
"react-json-editor-ajrm": "^2.5.6"
2. What operating system and processor architecture are you using? *REQUIRED
windows
3. What did you do? *REQUIRED
Report a bug.
I use the command $ yarn add react-json-editor-ajrm and get the error:
Could not find a declaration file for module 'react-json-editor-ajrm'. 'D:test/node_modules/react-json-editor-ajrm/index.js' implicitly has an 'any' type.
Try `npm install @types/react-json-editor-ajrm` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-json-editor-ajrm';
I try the first function, use the command what '$ yarn add react-json-editor-ajrm @types/react-json-editor-ajrm --dev' to install again, but still failed.
4. What did you expect to see? *REQUIRED
successfully use it.
5. What did you see instead? *REQUIRED
Thanks for reading it.

**Comment by lvybriage** [comment]
When I install the react-router, I met the error message as this. Then I use the command '$ yarn add react-router@3.0.5 @types/react-router@3.0.5 --dev' instead of the command '$ yarn add react-router' to resolve the problem. But when I use ''$ yarn add react-json-editor-ajrm @types/react-json-editor-ajrm --dev'' to avoid the question, I get the error message 'error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-json-editor-ajrm: Not found".'

**Comment by PatrickSachs** [comment]
Hello @lvybriage 

We currently do not provide typings for this library. The recommended NPM package `@types/react-json-editor-ajrm` recommended by TypeScript thus does not exist.

As far as I am aware there are no immediate plans for official TypeScript support, but we'd be happy to accept PRs on this subject matter.
