### ISSUE TITLE
No initial value as string can be provided. 

### ISSUE THREAD

**Issue by minbelapps** [AndrewRedican/react-json-editor-ajrm#99]
The placeHolder should be only a valid Object, why?  User is entering text, so any text could be as initial value. For example, the data are provided from other systems and users some times needs to fix it manually. How to use your tool, if it's impossible to provide initial value?

Version:  2.5.9

**Comment by AndrewRedican** [comment]
Your use case is different.

This editor caters for the use case where you simply want to see some object like structure. It does provide syntax checking capabilities if the user wants to modify the object.

I have been working on the side for a pure syntax checker (decoupled from a user interface) which seems this might suit you better, but it is still work in progress.
